add_newline = false

[character]
symbol = "âœ"
error_symbol = "âœ—"
use_symbol_for_status = true

[directory]
truncation_length = 5

[git_branch]
symbol = "\ue725 "

[kubernetes]
symbol = "â›µ "
style = "dim green"
disabled = false

[package]
symbol = "ğŸ "